version: '3.8'
services:
  # PostgreSQL コンテナの設定
  db:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schemaspy-sample

networks:
  schemaspy-sample:
    external: true
